#FROM mcr.microsoft.com/dotnet/core/sdk:2.2 as build
FROM docker-spv.artifactory.gscorp.ad/sonar-netcore:2.2

ENV http_proxy http://proxybc.gscorp.ad:8080
ENV https_proxy https://proxybc.gscorp.ad:8080

#COPY build.config/cert/ca.crt /usr/local/share/ca-certificates/spv-ca.crt
#RUN cat /usr/local/share/ca-certificates/spv-ca.crt >> /etc/ssl/certs/ca-certificates.crt

WORKDIR /src

COPY . ./
COPY ./applymodel.sh ./applymodel.sh

RUN rm global.json

#ENV PATH="${PATH}:/root/.dotnet/tools"
#RUN dotnet tool install -g dotnet-sonarscanner

RUN dotnet-sonarscanner begin /k:"api-extractaciones" /d:sonar.login="9db8d1fffdb9c6d26d14f2ab0946ade062c24370" /d:sonar.host.url="https://sonarqube.gscorp.ad"
RUN dotnet build Extractaciones.sln
RUN dotnet-sonarscanner end /d:sonar.login="9db8d1fffdb9c6d26d14f2ab0946ade062c24370"
